# ForgeOS Kitty profile
font_family JetBrainsMono Nerd Font
font_size 12.0
background_opacity 0.92
dynamic_background_opacity yes
confirm_os_window_close 0
scrollback_lines 20000
enable_audio_bell no
window_padding_width 8
cursor_shape beam
tab_bar_style powerline
active_tab_foreground #0b0b0f
active_tab_background #f97316
inactive_tab_foreground #d4d4d8
inactive_tab_background #18181b
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+f launch --type=overlay --stdin-source=@screen_scrollback fzf
